const LEVEL1 = new Level(
  [],
  [
    new Ground(-720 * 9, globalThis.keyboard),
    new Ground(-720 * 8, globalThis.keyboard),
    new Ground(-720 * 7, globalThis.keyboard),
    new Ground(-720 * 6, globalThis.keyboard),
    new Ground(-720 * 5, globalThis.keyboard),
    new Ground(-720 * 4, globalThis.keyboard),
    new Ground(-720 * 3, globalThis.keyboard),
    new Ground(-720 * 2, globalThis.keyboard),
    new Ground(-720, globalThis.keyboard),
    new Ground(0, globalThis.keyboard),
    new Ground(720, globalThis.keyboard),
    new Ground(720 * 2, globalThis.keyboard),
    new Ground(720 * 3, globalThis.keyboard),
    new Ground(720 * 4, globalThis.keyboard),
    new Ground(720 * 5, globalThis.keyboard),
    new Ground(720 * 6, globalThis.keyboard),
    new Ground(720 * 7, globalThis.keyboard),
    new Ground(720 * 8, globalThis.keyboard),
    new Ground(720 * 9, globalThis.keyboard)
  ],
  [
    new Foreground(-720 * 9, globalThis.keyboard),
    new Foreground(-720 * 8, globalThis.keyboard),
    new Foreground(-720 * 7, globalThis.keyboard),
    new Foreground(-720 * 6, globalThis.keyboard),
    new Foreground(-720 * 5, globalThis.keyboard),
    new Foreground(-720 * 4, globalThis.keyboard),
    new Foreground(-720 * 3, globalThis.keyboard),
    new Foreground(-720 * 2, globalThis.keyboard),
    new Foreground(-720, globalThis.keyboard),
    new Foreground(0, globalThis.keyboard),
    new Foreground(720, globalThis.keyboard),
    new Foreground(720 * 2, globalThis.keyboard),
    new Foreground(720 * 3, globalThis.keyboard),
    new Foreground(720 * 4, globalThis.keyboard),
    new Foreground(720 * 5, globalThis.keyboard),
    new Foreground(720 * 6, globalThis.keyboard),
    new Foreground(720 * 7, globalThis.keyboard),
    new Foreground(720 * 8, globalThis.keyboard),
    new Foreground(720 * 9, globalThis.keyboard)
  ],
  [
    new MiddleDecor(-720 * 9, globalThis.keyboard),
    new MiddleDecor(-720 * 8, globalThis.keyboard),
    new MiddleDecor(-720 * 7, globalThis.keyboard),
    new MiddleDecor(-720 * 6, globalThis.keyboard),
    new MiddleDecor(-720 * 5, globalThis.keyboard),
    new MiddleDecor(-720 * 4, globalThis.keyboard),
    new MiddleDecor(-720 * 3, globalThis.keyboard),
    new MiddleDecor(-720 * 2, globalThis.keyboard),
    new MiddleDecor(-720, globalThis.keyboard),
    new MiddleDecor(0, globalThis.keyboard),
    new MiddleDecor(720, globalThis.keyboard),
    new MiddleDecor(720 * 2, globalThis.keyboard),
    new MiddleDecor(720 * 3, globalThis.keyboard),
    new MiddleDecor(720 * 4, globalThis.keyboard),
    new MiddleDecor(720 * 5, globalThis.keyboard),
    new MiddleDecor(720 * 6, globalThis.keyboard),
    new MiddleDecor(720 * 7, globalThis.keyboard),
    new MiddleDecor(720 * 8, globalThis.keyboard),
    new MiddleDecor(720 * 9, globalThis.keyboard)
  ],
  [
    new BackgroundObject(-720 * 9, globalThis.keyboard),
    new BackgroundObject(-720 * 8, globalThis.keyboard),
    new BackgroundObject(-720 * 7, globalThis.keyboard),
    new BackgroundObject(-720 * 6, globalThis.keyboard),
    new BackgroundObject(-720 * 5, globalThis.keyboard),
    new BackgroundObject(-720 * 4, globalThis.keyboard),
    new BackgroundObject(-720 * 3, globalThis.keyboard),
    new BackgroundObject(-720 * 2, globalThis.keyboard),
    new BackgroundObject(-720, globalThis.keyboard),
    new BackgroundObject(0, globalThis.keyboard),
    new BackgroundObject(720, globalThis.keyboard),
    new BackgroundObject(720 * 2, globalThis.keyboard),
    new BackgroundObject(720 * 3, globalThis.keyboard),
    new BackgroundObject(720 * 4, globalThis.keyboard),
    new BackgroundObject(720 * 5, globalThis.keyboard),
    new BackgroundObject(720 * 6, globalThis.keyboard),
    new BackgroundObject(720 * 7, globalThis.keyboard),
    new BackgroundObject(720 * 8, globalThis.keyboard),
    new BackgroundObject(720 * 9, globalThis.keyboard)
  ]
);
