const LEVEL1 = new Level(
  [],
  [
    new Ground(-719 * 9, globalThis.keyboard),
    new Ground(-719 * 8, globalThis.keyboard),
    new Ground(-719 * 7, globalThis.keyboard),
    new Ground(-719 * 6, globalThis.keyboard),
    new Ground(-719 * 5, globalThis.keyboard),
    new Ground(-719 * 4, globalThis.keyboard),
    new Ground(-719 * 3, globalThis.keyboard),
    new Ground(-719 * 2, globalThis.keyboard),
    new Ground(-719, globalThis.keyboard),
    new Ground(0, globalThis.keyboard),
    new Ground(719, globalThis.keyboard),
    new Ground(719 * 2, globalThis.keyboard),
    new Ground(719 * 3, globalThis.keyboard),
    new Ground(719 * 4, globalThis.keyboard),
    new Ground(719 * 5, globalThis.keyboard),
    new Ground(719 * 6, globalThis.keyboard),
    new Ground(719 * 7, globalThis.keyboard),
    new Ground(719 * 8, globalThis.keyboard),
    new Ground(719 * 9, globalThis.keyboard),
    new Ground(719 * 10, globalThis.keyboard),
    new Ground(719 * 11, globalThis.keyboard),
    new Ground(719 * 12, globalThis.keyboard),
    new Ground(719 * 13, globalThis.keyboard),
    new Ground(719 * 14, globalThis.keyboard),
    new Ground(719 * 15, globalThis.keyboard),
    new Ground(719 * 16, globalThis.keyboard),
    new Ground(719 * 17, globalThis.keyboard)
  ],
  [
    new Foreground(-720 * 9, globalThis.keyboard),
    new Foreground(-720 * 8, globalThis.keyboard),
    new Foreground(-720 * 7, globalThis.keyboard),
    new Foreground(-720 * 6, globalThis.keyboard),
    new Foreground(-720 * 5, globalThis.keyboard),
    new Foreground(-720 * 4, globalThis.keyboard),
    new Foreground(-720 * 3, globalThis.keyboard),
    new Foreground(-720 * 2, globalThis.keyboard),
    new Foreground(-720, globalThis.keyboard),
    new Foreground(0, globalThis.keyboard),
    new Foreground(720, globalThis.keyboard),
    new Foreground(720 * 2, globalThis.keyboard),
    new Foreground(720 * 3, globalThis.keyboard),
    new Foreground(720 * 4, globalThis.keyboard),
    new Foreground(720 * 5, globalThis.keyboard),
    new Foreground(720 * 6, globalThis.keyboard),
    new Foreground(720 * 7, globalThis.keyboard),
    new Foreground(720 * 8, globalThis.keyboard),
    new Foreground(720 * 9, globalThis.keyboard),
    new Foreground(720 * 10, globalThis.keyboard),
    new Foreground(720 * 11, globalThis.keyboard),
    new Foreground(720 * 12, globalThis.keyboard),
    new Foreground(720 * 13, globalThis.keyboard),
    new Foreground(720 * 14, globalThis.keyboard)
  ],
  [
    new MiddleDecor(-720 * 9, globalThis.keyboard),
    new MiddleDecor(-720 * 8, globalThis.keyboard),
    new MiddleDecor(-720 * 7, globalThis.keyboard),
    new MiddleDecor(-720 * 6, globalThis.keyboard),
    new MiddleDecor(-720 * 5, globalThis.keyboard),
    new MiddleDecor(-720 * 4, globalThis.keyboard),
    new MiddleDecor(-720 * 3, globalThis.keyboard),
    new MiddleDecor(-720 * 2, globalThis.keyboard),
    new MiddleDecor(-720, globalThis.keyboard),
    new MiddleDecor(0, globalThis.keyboard),
    new MiddleDecor(720, globalThis.keyboard),
    new MiddleDecor(720 * 2, globalThis.keyboard),
    new MiddleDecor(720 * 3, globalThis.keyboard),
    new MiddleDecor(720 * 4, globalThis.keyboard),
    new MiddleDecor(720 * 5, globalThis.keyboard),
    new MiddleDecor(720 * 6, globalThis.keyboard),
    new MiddleDecor(720 * 7, globalThis.keyboard),
    new MiddleDecor(720 * 8, globalThis.keyboard),
    new MiddleDecor(720 * 9, globalThis.keyboard),
    new MiddleDecor(720 * 10, globalThis.keyboard),
    new MiddleDecor(720 * 11, globalThis.keyboard),
    new MiddleDecor(720 * 12, globalThis.keyboard),
    new MiddleDecor(720 * 13, globalThis.keyboard),
    new MiddleDecor(720 * 14, globalThis.keyboard)
  ],
  [
    new BackgroundObject(-719 * 9, globalThis.keyboard),
    new BackgroundObject(-719 * 8, globalThis.keyboard),
    new BackgroundObject(-719 * 7, globalThis.keyboard),
    new BackgroundObject(-719 * 6, globalThis.keyboard),
    new BackgroundObject(-719 * 5, globalThis.keyboard),
    new BackgroundObject(-719 * 4, globalThis.keyboard),
    new BackgroundObject(-719 * 3, globalThis.keyboard),
    new BackgroundObject(-719 * 2, globalThis.keyboard),
    new BackgroundObject(-719, globalThis.keyboard),
    new BackgroundObject(0, globalThis.keyboard),
    new BackgroundObject(719, globalThis.keyboard),
    new BackgroundObject(719 * 2, globalThis.keyboard),
    new BackgroundObject(719 * 3, globalThis.keyboard),
    new BackgroundObject(719 * 4, globalThis.keyboard),
    new BackgroundObject(719 * 5, globalThis.keyboard),
    new BackgroundObject(719 * 6, globalThis.keyboard),
    new BackgroundObject(719 * 7, globalThis.keyboard),
    new BackgroundObject(719 * 8, globalThis.keyboard),
    new BackgroundObject(719 * 9, globalThis.keyboard),
    new BackgroundObject(719 * 10, globalThis.keyboard),
    new BackgroundObject(719 * 11, globalThis.keyboard),
    new BackgroundObject(719 * 12, globalThis.keyboard),
    new BackgroundObject(719 * 13, globalThis.keyboard),
    new BackgroundObject(719 * 14, globalThis.keyboard)
  ],
  [new HealthCoin(800), new HealthCoin(450)],
  [
    new ManaCoin(500),
    new ManaCoin(650),
    new ManaCoin(780),
    new ManaCoin(1050),
    new ManaCoin(1200),
    new ManaCoin(1500)
  ]
);
